version: '3.7'
services:
  web-prod:
    image: atho-tech-enterprise-web:prod
    container_name: atho-tech-enterprise-web-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '${PORT}:80'
    env_file:
      - .env
